// dart-webext -- shared Dart library for browser extensions
// Copyright (C) 2026 Heiko Zimmermann
// SPDX-License-Identifier: BSD-3-Clause

// GENERATED FILE -- do not edit by hand.
//
// Generated by tool/generate_cloudflare_ranges.dart, which fetches
// Cloudflare's published ranges, validates every line through the
// library's own IpAddress.tryParse and aborts on anything unexpected.
//
//   source:  https://www.cloudflare.com/ips-v4
//            https://www.cloudflare.com/ips-v6
//   fetched: 2026-08-31
//
// The entries keep the order of the published lists, and every entry
// carries the published line verbatim as a trailing comment, so a later
// guard can compare this state against the source without guessing.

/// Cloudflare's published IP ranges, compiled in.
///
/// Regenerate with `tool/generate_cloudflare_ranges.dart`; the header
/// comment of this file carries the source URLs and the fetch date.
library;

import 'ip_address.dart';

/// The published IPv4 ranges, in published order. Source and fetch date
/// are in the header comment of this file.
const List<CidrV4> cloudflareRangesV4 = [
  CidrV4(173, 245, 48, 0, 20), // 173.245.48.0/20
  CidrV4(103, 21, 244, 0, 22), // 103.21.244.0/22
  CidrV4(103, 22, 200, 0, 22), // 103.22.200.0/22
  CidrV4(103, 31, 4, 0, 22), // 103.31.4.0/22
  CidrV4(141, 101, 64, 0, 18), // 141.101.64.0/18
  CidrV4(108, 162, 192, 0, 18), // 108.162.192.0/18
  CidrV4(190, 93, 240, 0, 20), // 190.93.240.0/20
  CidrV4(188, 114, 96, 0, 20), // 188.114.96.0/20
  CidrV4(197, 234, 240, 0, 22), // 197.234.240.0/22
  CidrV4(198, 41, 128, 0, 17), // 198.41.128.0/17
  CidrV4(162, 158, 0, 0, 15), // 162.158.0.0/15
  CidrV4(104, 16, 0, 0, 13), // 104.16.0.0/13
  CidrV4(104, 24, 0, 0, 14), // 104.24.0.0/14
  CidrV4(172, 64, 0, 0, 13), // 172.64.0.0/13
  CidrV4(131, 0, 72, 0, 22), // 131.0.72.0/22
];

/// The published IPv6 ranges, in published order. Source and fetch date
/// are in the header comment of this file.
const List<CidrV6> cloudflareRangesV6 = [
  CidrV6(0x2400, 0xcb00, 0, 0, 0, 0, 0, 0, 32), // 2400:cb00::/32
  CidrV6(0x2606, 0x4700, 0, 0, 0, 0, 0, 0, 32), // 2606:4700::/32
  CidrV6(0x2803, 0xf800, 0, 0, 0, 0, 0, 0, 32), // 2803:f800::/32
  CidrV6(0x2405, 0xb500, 0, 0, 0, 0, 0, 0, 32), // 2405:b500::/32
  CidrV6(0x2405, 0x8100, 0, 0, 0, 0, 0, 0, 32), // 2405:8100::/32
  CidrV6(0x2a06, 0x98c0, 0, 0, 0, 0, 0, 0, 29), // 2a06:98c0::/29
  CidrV6(0x2c0f, 0xf248, 0, 0, 0, 0, 0, 0, 32), // 2c0f:f248::/32
];
